### ISSUE TITLE
Addition to Joomla Tech. Requirements

### ISSUE THREAD

**Issue by gwsdesk** [joomla/downloads.joomla.org#112]
https://downloads.joomla.org/technical-requirements#footnote-3xMySQL I believe (thoughts) that we should add here that [7] for servers that use PHP7, MySQL is not longer supported and MySQLi is required

**Comment by zero-24** [comment]
But Is'nt that a restriction of PHP and not Joomla as the extension is dropped?

**Comment by gwsdesk** [comment]
I do agree with that remark but we do see a lot of questions and issues on the forums so it makes sense to make people aware as a site-note I believe since at present they blame Joomla

**Comment by mbabker** [comment]
Keep in mind too that Joomla has a fair bit of logic in place so that if your global config is set to use the deprecated `ext/mysql` extension, we try to move you to one of the other supported variations and only fail if both MySQLi and PDO MySQL are disabled too.

https://github.com/joomla/joomla-cms/blob/4711ba1ede505345ef822777a3643d0472be7e30/libraries/joomla/database/driver.php#L256-L293

**Comment by gwsdesk** [comment]
Yep which is a cool PR but it does not resolves the issue that people change settings to PHP7 or change host who runs PHP7 without having the needed MySQLi in place so the site crashes. It is simply a little piece of info though needed at present (just search the Joomla forums and see how many issues are related to this very simple piece of info) I do agree it is not Joomla but that is also not fact for the footnotes point 1 - 6 at present

**Comment by mbabker** [comment]
I'm going to close this as won't fix.  The tech requirements page honestly isn't the best place to get into technical level distinctions of what PHP extensions are or are not supported in certain configurations (mainly the combination of Joomla and PHP versions).  A page like https://docs.joomla.org/Optional_Technical_Requirements (which is linked from the tech requirements page) is probably a better place to get into more in-depth technical matters like this.  And as noted, even if Joomla is still configured to use "mysql" as the driver (which points to the deprecated/abandoned `ext/mysql`) on a PHP 7 server, it still takes reasonable steps to try and use one of the other supported PHP extensions and only fails in that configuration if your server doesn't have either of `ext/mysqli` or `ext/pdo` (with MySQL support) enabled.
