### ISSUE TITLE
Feature Request: Release Notices

### ISSUE THREAD

**Issue by mbabker** [joomla/downloads.joomla.org#115]
These came out of a Glip chat, posting here so the information is not lost:

> - Place a notice at the top of all the old/previous Joomla download pages, that is something like this: Note that the latest version of Joomla is available here: https://downloads.joomla.org/cms
>
> - On the above page, add an info/notice box with text such as: Important information when upgrading Joomla from 1.0, 1.5, 3.5 and [whatever version needs caution], and link that to the Wiki page dealing with upgrades/migrations.  The reason I'm suggesting linking the first notice to this CMS page, is that  it makes it easier for those with old versions of Joomla to see their version in context of all the other versions. (it makes it clearer they are using an unsupported version)... and it does not clutter the Latest Release page.

**Comment by conconnl** [comment]
Merged
