### ISSUE TITLE
[jdown] 404 on the page https://downloads.joomla.org/ca/ the translations

### ISSUE THREAD

**Issue by zero-24** [joomla/downloads.joomla.org#116]
On the CA Page: https://downloads.joomla.org/ca/

The link /button `Télécharger les paquets de langue` points to https://downloads.joomla.org/ca/translations/fr-ca wich is a 404.

All other pages seams to link to: https://community.joomla.org/translations.html

**Comment by mbabker** [comment]
Fixed

**Comment by zero-24** [comment]
Thanks 👍
