### ISSUE TITLE
Cross origin requests are blocked

### ISSUE THREAD

**Issue by C-Lodder** [joomla/downloads.joomla.org#122]
```
Joomla.request({
    url: 'https://downloads.joomla.org/api/v1/releases/cms',
    onSuccess: function(response, xhr) {
        console.log(response);
    }
})
```

I'd normally expected a response with this, however I'm getting the following:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://downloads.joomla.org/api/v1/releases/cms. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://downloads.joomla.org/api/v1/releases/cms. (Reason: CORS request did not succeed).

Same applies for `http://update.joomla.org/core/list.xml`.

**Comment by mbabker** [comment]
@zero-24 any ideas here?  Something to do with our CSP changes, something on the local site, or something we just haven't implemented support for?  Our API endpoints (`https://downloads.joomla.org/api` and `https://developer.joomla.org/stats`) and the update server should be a bit more friendly as it relates to CORS compared to other pages and assets.

**Comment by zero-24** [comment]
Has nothing todo with CSP or the other headers we have set.

But I have just set the following headers:

```
##################### Security Header #####################
<IfModule mod_headers.c>
	# Allow CORS
	Header always set Access-Control-Allow-Origin "*"
	Header always set Access-Control-Allow-Headers "*"
</IfModule>
##################### Security Header #####################
```

[for the api folder](https://github.com/joomla/downloads.joomla.org/pull/123) where can I find the folder for the stats api?

**Comment by zero-24** [comment]
Ah got confused downloads vs developer .. :)

**Comment by zero-24** [comment]
Done PRs there too.
