### ISSUE TITLE
Update the Community Portal listing for 3.x language packages

### ISSUE THREAD

**Issue by mbabker** [joomla/downloads.joomla.org#20]
Maybe this should just link direct to the site from the main translations page and redirect the listing page?

**Comment by Sandra97** [comment]
Regarding all translation pages on cjo,

We can add to the FAQs page:
[FAQ-toadd.txt](https://github.com/joomla/downloads.joomla.org/files/860058/FAQ-toadd.txt)

This page can go directly to the trash: https://community.joomla.org/translations/593-typical-language-file-headers.html

I can merge this one: https://community.joomla.org/translations/544-joomla-project-translation-and-localization-policy.html to JDocs and ask the Core Translation Team to update it (with a bit of luck it will be updated before next century).

I didn't find any other elements to keep.

**Comment by conconnl** [comment]
Processed in the new system, site and other levels.

**Comment by HLeithner** [comment]
Thanks @conconnl I'm closing this.
