### ISSUE TITLE
SEO Data for 3.x language packages

### ISSUE THREAD

**Issue by mbabker** [joomla/downloads.joomla.org#21]
Get all of the menu item and SEO data for this section written up.

**Comment by Sandra97** [comment]
Franglish SEO for the 4 main menu items. 
[Translations Menu Items - SEO.docx](https://github.com/joomla/downloads.joomla.org/files/861301/Translations.Menu.Items.-.SEO.docx)

**Comment by conconnl** [comment]
Processed in the new component.

**Comment by HLeithner** [comment]
Thanks @conconnl I'm closing this.
