### ISSUE TITLE
J4 Release - Update FAQ (reminder)

### ISSUE THREAD

**Issue by conconnl** [joomla/downloads.joomla.org#259]
The FAQ on the site needs to be updated. https://downloads.joomla.org/faqs
This can only be done after the forum is extended.
File: https://github.com/joomla/downloads.joomla.org/blob/master/language/en-GB/en-GB.page_faqs.ini

Also the link to the translations and some other small things.

**Comment by basit9958** [comment]
@conconnl  Please drop the link of IRC channel

**Comment by conconnl** [comment]
Not sure what you mean.
It's already solved, forgot to close my own reminder.
