### ISSUE TITLE
CMS Api Endpoint returns also language packs

### ISSUE THREAD

**Issue by zero-24** [joomla/downloads.joomla.org#271]
The [CMS API Endpoint](https://downloads.joomla.org/api-docs/#endpointAccordion_releases) should return all CMS releases but right now returns all language packs too: https://downloads.joomla.org/api/v1/releases/cms/

I think the reason is this line here: https://github.com/joomla/downloads.joomla.org/blob/master/libraries/api/controller/releases/cms.php#L39

I have looked up the correct IDs but I'm not sure how to correctly use the filter here?

Category ID | Name
------------ | -------------
268 | Joomla 4
4 | Joomla 3
3 | Joomla 2.5
2 | Joomla 1.5
1 | Joomla 1.0

Can you help here @HLeithner @wilsonge @Llewellynvdm ?

**Comment by Llewellynvdm** [comment]
I also open this issue here https://github.com/joomla/joomla-websites/issues/1641

SO I have already debugged this and it really is a matter of filtering the CMS from the language packs.

The real issue is that the categories are not that ideal, and will result in hard coded ID's... checkout [my comments here](https://github.com/joomla/joomla-websites/issues/1641#issuecomment-895230877).

**Comment by Llewellynvdm** [comment]
So an ugly hack.. and serious dependency issue will be to add the following code on [line 39](https://github.com/joomla/downloads.joomla.org/blob/master/libraries/api/controller/releases/cms.php#L39):
```php
->category_id([1,2,3,4,268])
```

**Comment by Llewellynvdm** [comment]
Or to use some other form of grouping like I showed with the `->visualgroup_id(1)` option. Also painful but at-least this way we don't need to update the code with each new release.

I deal would be to have a field that we can in the GUI use to tag specifically these releases, with even more info in regards to what we may need in the new docker image builder. But okay I think for now we can just add a simple fix, and circle around to this again when we look at improving the API.

I mean we are moving to Joomla 4 soon right... and then al things new :+1:

**Comment by zero-24** [comment]
PR: https://github.com/joomla/downloads.joomla.org/pull/272 i like the `->visualgroup_id(1)` more too, thanks.
