### ISSUE TITLE
https://downloads.joomla.org/api-docs/ have no Layout

### ISSUE THREAD

**Issue by Franzwohlkoenig** [joomla/downloads.joomla.org#285]
https://downloads.joomla.org/api-docs/ show:

![1](https://user-images.githubusercontent.com/89642616/135742453-cc512fb5-2760-4858-86af-a3b18bac079f.png)

Test in different languages and firefox, safari (all latest) – same result.

**Comment by conconnl** [comment]
Thanks @Franzwohlkoenig
