### ISSUE TITLE
API-Docs Header and Footer menu

### ISSUE THREAD

**Issue by conconnl** [joomla/downloads.joomla.org#287]
The API-Docs header and footer menu are outdated as they are hardcoded.

**Comment by Alam9835** [comment]
i want to work on this

**Comment by HLeithner** [comment]
> i want to work on this

you are welcome

**Comment by Alam9835** [comment]
> > i want to work on this
> 
> you are welcome

can you please guide me on how to proceed with it I will be very grateful

**Comment by HLeithner** [comment]
@conconnl we are talking about https://downloads.joomla.org/api-docs/ right?

@Alam9835 you can find the code for this at https://github.com/joomla/downloads.joomla.org/tree/master/api-docs

I personal didn't looked at the code so have no idea how to change this, but I would expect 2 ways, update the code onetime statically with a pull request matching the current header and footer code.
Or write a github action todo this regular.

**Comment by conconnl** [comment]
Correct, this file: https://github.com/joomla/downloads.joomla.org/blob/master/api-docs/index.html

**Comment by Alam9835** [comment]
> The API-Docs header and footer menu are outdated as they are hardcoded.

I am currently working on this can you please suggest to me what changes are needed or you want?

**Comment by conconnl** [comment]
Footer loaded on the other sites: https://cdn.joomla.org/template/renderer.php?section=footer&language=en-GB
Header loaded on the other sites: https://cdn.joomla.org/template/renderer.php?section=menu&language=en-GB

It doesn't mean they just fit in this website, automated or other wise.
It's possible the changes just need to be compared and applied manually.

**Comment by Alam9835** [comment]
> Footer loaded on the other sites: https://cdn.joomla.org/template/renderer.php?section=footer&language=en-GB Header loaded on the other sites: https://cdn.joomla.org/template/renderer.php?section=menu&language=en-GB
> 
> It doesn't mean they just fit in this website, automated or other wise. It's possible the changes just need to be compared and applied manually.

you want these changes on this site( https://downloads.joomla.org/api-docs/ ). am I correct

**Comment by conconnl** [comment]
I think we should as the api-docs site has outdated links, which can create issues for the users.

**Comment by Alam9835** [comment]
> I think we should as the api-docs site has outdated links, which can create issues for the users.

ok I will make the changes

**Comment by Alam9835** [comment]
I have done the required changes please merge my PR #294

**Comment by Alam9835** [comment]
I have updated please check my PR #294

**Comment by conconnl** [comment]
PR Merged
