### ISSUE TITLE
404 Link to the "optional requirements" on the technical requirements page

### ISSUE THREAD

**Issue by zero-24** [joomla/downloads.joomla.org#298]
![image](https://user-images.githubusercontent.com/2596554/154790201-943152a9-72ec-4c57-9dc1-7f1bad6f0c09.png)

Please replace that link here https://downloads.joomla.org/technical-requirements with:
https://docs.joomla.org/J3.x:Optional_Technical_Requirements
and
https://docs.joomla.org/J4.x:Optional_Technical_Requirements

**Comment by Amishakumari544** [comment]
Hi , can i work on this issue?

**Comment by zero-24** [comment]
Hi, the probelm is that you would need access to the downloads portal backend which only @HLeithner has. So yes its open to work but its not something someone else than Harald can da sadly :)

**Comment by HLeithner** [comment]
Acually you can work on it' just create a PR against https://github.com/joomla/downloads.joomla.org/blob/master/www/templates/joomla/html/com_content/article/requirements.php but I think it's only a language string you have to make the PR against https://github.com/joomla/downloads.joomla.org/blob/master/www/language/en-GB/en-GB.page_technical_requirements.ini#L15

it can then be translated with crowdin: https://joomla.crowdin.com/translate/a0c5623de99091c49ba889253566bfa9/2232/engb-de/496?filter=basic&value=0#q=TECHNICAL_REQUIREMENTS_CONFIGURATION_OPTIONS_OUTRO (german translation

**Comment by koksesankalp** [comment]
hey @zero-24  @HLeithner if this is still open I would love to work on this.

**Comment by HLeithner** [comment]
@koksesankalp of course just create a PR as mentioned above
