### ISSUE TITLE
[jdown] Download of language packs for J5 is broken

### ISSUE THREAD

**Issue by max123kl** [joomla/downloads.joomla.org#343]
The download links for the Joomla! 5 language packs do not work.

If the environment language is set to a non-English language (e.g. Spanish https://downloads.joomla.org/es/language-packs/translation5), an error page is displayed when trying to download (see screenshot).

![download-language-pack](https://github.com/joomla/downloads.joomla.org/assets/853497/e0045af1-7f03-42ad-9007-9b88d32272b0)

**If you switch to the English page, the download works**

The issue was reported by user Josean Telleria on Mattermost and is confirmed by me.

**Comment by wilsonge** [comment]
This isn't a component bug - but a error in the way the multi-lingual menu's were structured on the site when the J5 entries were created. Closing in favour of the bug tracked in https://github.com/joomla/joomla-websites/issues/1956
