### ISSUE TITLE
Extensions - Missing the name in the title

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/downloads.joomla.org#75]
In the extension section, the name of the open extension is not present in the tab title.

![immagine](https://user-images.githubusercontent.com/733133/28501813-3802ff92-6fe4-11e7-9a90-3ec3ab355c55.png)

https://downloads.joomla.org/extensions/weblinks

**Comment by Sandra97** [comment]
Works fine for me. Name of the extension is displayed

**Comment by mbabker** [comment]
I just pushed a change to fix that view.  Fixing one more.

**Comment by mbabker** [comment]
https://github.com/joomla/downloads.joomla.org/compare/eeb592a2600c105256abedba740272385e581127...master has all the changes needed, including the language strings added.  If those are good, we can push it over to Crowdin and work on getting those updated.

**Comment by Sandra97** [comment]
Good for me!

**Comment by jeckodevelopment** [comment]
Thanks!
